# action.yml
name: "Splunk AppInspect"
description: "Run Splunk App inspect API Calls on Add-on"
inputs:
  username:
    description: username for appinspect authentication
    required: true
  password:
    description: password for appinspect authentication
    required: true
  app_path:
    description: path to addon
    required: true
  included_tags:
    description: comma seperated list of tags to run appinspect scans with
    default: ""
    required: false
  excluded_tags:
    description: comma seperated list of tags to be excluded from appinspect scans
    default: ""
    required: false
runs:
  using: "docker"
  image: docker://ghcr.io/splunk/appinspect-api-action/appinspect-api-action:v3.0.0
#  image: docker://ghcr.io/splunk/appinspect-api-action/appinspect-api-action:v1.0.0
